@startuml blackjack

BlackjackGame -- Player
BlackjackGame -- Dealer
BlackjackGame -- Deck
Player -- Deck
Dealer -- Deck
Deck *-- Card

skinparam classAttributeIconSize 0

class BlackjackGame {
    +startGame(): void
    -getMessage(): string
}

class Player {
    +init(): void
    +drawCards(Deck $deck): array
}

class Dealer {
    +init(): void
    +drawCards(Deck $deck): array
}

class Deck {
    -array cards
    +createNewDeck(): array
    +drawCards(): array
}

class Card {
    -string suit
    -int number
    +getSuit(): string
    +getNumber(): string
}

@enduml
