@startuml blackjack

skinparam actorStyle awesome

participant Main          as Main
participant BlackjackGame as Game
actor       CpuPlayer     as C
actor       HumPlayer     as P #pink
actor       Dealer        as D
participant Deck          as Deck
participant Card          as Card
participant HandJudger    as HandJudger

group ゲームの開始
    Main -> Game : ゲームを開始する
    activate Game

    group #FFEECC  ゲームの導入
        Game -> HandJudger : HandJudgerを作成する

        Game -> Deck : デッキを作成する
        activate Deck
        Deck -> Card : カード52枚をシャッフル
        activate Card
        Card --> Deck : シャッフルしたカード
        deactivate Card
        deactivate Deck

        Game -> D : ディーラーを作成
        activate D
        D -> D : 初期化
        deactivate D

        Game -> P : プレイヤーを作成
        activate P
        P -> P : 初期化
        deactivate P

    Game -> Game : メッセージを表示
        deactivate Game

        note right Game
            プレイヤーの人数(1人~3人)を選択してください(1~3の数値を入力)
            ブラックジャックを開始します。
        end note

        Game -> C : CPUを作成
        activate C
        C -> C : 初期化
        deactivate C

        Game -> C : CPU手札を取得
        activate C
        C -> Deck : カードを2枚とる
        activate Deck
        Deck --> C : カードを2枚返す
        deactivate Deck
        C -> C : 合計点を更新する
        C --> Game : CPU手札
        deactivate C

        Game -> P : プレイヤー手札を取得
        activate P
        P -> Deck : カードを2枚とる
        activate Deck
        Deck --> P : カードを2枚返す
        deactivate Deck
        P -> P : 合計点を更新する
        P --> Game : プレイヤー手札
        deactivate P

        Game -> D : ディーラー手札を取得
        activate D
        D -> Deck : カードを2枚とる
        activate Deck
        Deck  --> D : カードを2枚返す
        deactivate Deck
        D -> D : 合計点を更新する
        D --> Game : ディーラー手札
        deactivate D

        Game -> Game : メッセージを返す
        deactivate Game

        note right Game
            ブラックジャックを開始します。

            あなたの引いたカードはハートの7です。
            あなたの引いたカードはクラブの8です。

            CPUの引いたカードはハートの3です。
            CPUの引いたカードはスペードの10です。

            ディーラーの引いたカードはダイヤのQです。
            ディーラーの引いた2枚目のカードはわかりません。

            あなたの現在の得点は15です。カードを引きますか？（y/N）
        end note
    end


alt #FFDDCC プレイヤーのターン
    loop  while 'y'
        Game -> P : プレイヤー手札を取得
        activate P
        P -> Deck : カードを1枚とる
        activate Deck
        Deck --> P : カードを1枚返す
        deactivate Deck
        P -> P : 合計点を更新する
        P --> Game : プレイヤー手札
        deactivate P

        Game -> Game : メッセージを返す
        deactivate Game

        note right Game
            あなたの引いたカードはスペードの５です。
        end note

        alt 合計が21以内の場合
            Game -> Game : メッセージを返す
            deactivate Game
            note right Game
                あなたの現在の得点は20です。カードを引きますか？（y/N）
            end note

        else 合計が21を超えた場合
            Game -> Game : メッセージを返す
            deactivate Game
            note right Game #FFAAAA
                あなたの現在の得点は22です。バーストしました。
                残念！あなたの負けです。
            end note
            Game -> Game : ゲームを終了する
            deactivate Game
        end
    end

    else #FFCCCC CPUのターン
        loop while 合計17以上になるまで
            Game -> C : CPU手札を取得
            activate C
            C -> Deck : カードを1枚とる
            activate Deck
            Deck  --> C : カードを1枚返す
            deactivate Deck
            C -> C : 合計点を更新する
            C --> Game : CPU手札
            deactivate C

            Game -> Game : メッセージを返す
            deactivate Game

            note right Game
                CPUがカードを引きます。
                CPUの引いたカードはハートの5です。
            end note
        end

    else #FFCCCC ディーラーのターン
        Game -> Game : メッセージを返す
        deactivate Game
        note right Game
            ディーラーの引いた2枚目のカードはダイヤの2でした。
            ディーラーの現在の得点は12です。
        end note

        loop while 合計17以上になるまで
            Game -> D : ディーラー手札を取得
            activate D
            D -> Deck : カードを1枚とる
            activate Deck
            Deck  --> D : カードを1枚返す
            deactivate Deck
            D -> D : 合計点を更新する
            D --> Game : ディーラー手札
            deactivate D

            Game -> Game : メッセージを返す
            deactivate Game

            note right Game
                ディーラーがカードを引きます。
                ディーラーの引いたカードはクラブの5です。
            end note
        end
    end

    group #FEBBCC 勝敗判定

        Game -> Game : 得点発表メッセージを返す
        deactivate Game
        note right Game
            〇得点発表〇
            ディーラーの得点は17です。
            あなたの得点は17です。
            CPUプレイヤー1の得点は18です。
        end note

        Game -> HandJudger : 結果を取得
        activate HandJudger
        HandJudger --> Game : 結果をを返す
        deactivate HandJudger

        Game -> Game : 結果発表メッセージを返す
        deactivate Game
        note right Game
            〇結果発表〇
            あなたは引き分けです。
            CPUプレイヤー1の勝ちです。
        end note

        Game -> Game : 終了メッセージを返す
        deactivate Game
        note right Game
            ブラックジャックを終了します。
        end note

        Game -> Game : ゲームを終了する
    end
end
@enduml
